# Generated by Django 4.1.7 on 2023-04-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_sesson_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sesson_Year',
            new_name='Session_Year',
        ),
    ]
