# Generated by Django 4.1.7 on 2023-04-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='dmin',
            new_name='admin',
        ),
    ]
