# Generated by Django 4.1.7 on 2023-05-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_studentapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_notification',
            name='faculty_id',
        ),
        migrations.DeleteModel(
            name='Faculty_Feedback',
        ),
        migrations.DeleteModel(
            name='Faculty_Notification',
        ),
    ]
